build:
  image: bjodah/bjodahimg18dev:v1.2
  environment:
    - ASAN_SYMBOLIZER_PATH=/usr/lib/llvm-6.0/bin/llvm-symbolizer
    - ASAN_OPTIONS=symbolize=1
  commands:
    - bash -c '[[ $(python setup.py --version) =~ ^[0-9]+.* ]]'
    - ./scripts/ci.sh pygslodeiv2
    - (cd examples/; ipython3 nbconvert --to=html --ExecutePreprocessor.enabled=True --ExecutePreprocessor.timeout=300 *.ipynb)
    - (cd examples/; ../scripts/render_index.sh *.html)
    - ./scripts/generate_docs.sh
    - ./scripts/prepare_deploy.sh
    - PATH=/opt/miniconda3/bin:$PATH conda build conda-recipe
    - if grep "DO-NOT-MERGE!" -R . --exclude ".drone.yml"; then exit 1; fi

deploy:

  rsync:
    host: hera.physchem.kth.se
    port: 22
    user: pygslodeiv2
    source: deploy/
    target: ~
    recursive: true
    delete: false
