clone:
  depth: 2
  recursive: true
  submodule_override:
    external/anyode: git://github.com/bjodah/anyode.git

build:
  image: bjodah/bjodahimg20dev:v1.1.0
  environment:
    - ASAN_SYMBOLIZER_PATH=/usr/lib/llvm-10/bin/llvm-symbolizer
    - ASAN_OPTIONS=symbolize=1
  commands:
    - bash -c '[[ $(python3 setup.py --version) =~ ^[0-9]+.* ]]'
    - ./scripts/ci.sh pygslodeiv2
    - ./scripts/render_notebooks.sh examples/
    - (cd examples/; ../scripts/render_index.sh *.html)
    - ./scripts/generate_docs.sh
    - ./scripts/prepare_deploy.sh
    - if grep "DO-NOT-MERGE!" -R . --exclude ".drone.yml"; then exit 1; fi

deploy:

  rsync:
    host: hera.physchem.kth.se
    port: 22
    user: pygslodeiv2
    source: deploy/
    target: ~
    recursive: true
    delete: false
