{% set name = "pygslodeiv2" %}
{% set version = "0.6.0.git" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: ../

build:
  number: 0

requirements:
  build:
    - python
    - numpy
    - gsl
    - cython
  run:
    - python
    - numpy
    - gsl

test:
  imports:
    - {{ name }}
  requires:
    - pytest
  commands:
    - python -m pytest --pyargs {{ name }}

about:
  home: https://github.com/bjodah/{{ name }}
  license: GPL-3.0
  license_file: LICENSE
  summary: 'Python binding for odeiv2 interface from GNU Scientific Library (GSL)'
  doc_url: https://bjodah.github.io/{{ name }}

extra:
  recipe-maintainers:
    - bjodah
