{% set name = "pygslodeiv2" %}
{% set version = "0.9.0+git" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: ../

build:
  number: 0
  skip: True  # [win]
  skip: True  # [osx and py27]
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - toolchain
    - python
    - setuptools
    - pip
    - numpy 1.11.*
    - gsl
    - cython
  run:
    - python
    - numpy >=1.11
    - gsl

test:
  imports:
    - {{ name }}
  requires:
    - pytest
  commands:
    - python -m pytest --pyargs {{ name }}

about:
  home: https://github.com/bjodah/{{ name }}
  license: GPL-3.0
  license_file: LICENSE
  summary: 'Python binding for odeiv2 interface from GNU Scientific Library (GSL)'
  doc_url: https://bjodah.github.io/{{ name }}/latest

extra:
  recipe-maintainers:
    - bjodah
