package:
  name: pygslodeiv2
  version: 0.6.0.git

source:
  path: ../

build:
  number: 0

requirements:
  build:
    - python
    - numpy
    - gsl
    - cython
  run:
    - numpy
    - python
    - gsl

test:
  imports:
    - pygslodeiv2
  requires:
    - pytest

about:
  home: https://github.com/bjodah/pygslodeiv2
  license: GNU GPL v3
